#!/usr/bin/env python3
"""Fresh R1 copy, actual-owner host proof, and one compile-only fit measurement."""
import argparse
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

from r0f_group2_target_admission import ROOT, sha, section_inventory

BASE = ROOT / 'build/r0f/group2/target-admission/queue-ceu0y7ys'
PREFIX = 'src/diagnostics/r0f/'


def function(source, name):
    """Extract an exact definition, retaining its source body for host execution."""
    match = re.search(r'^(?:static )?(?:uint\d+_t|void) ' + name + r'\(', source, re.M)
    if not match:
        raise ValueError('Missing definition: ' + name)
    begin = source.index('{', match.start())
    depth = 1
    end = begin + 1
    while depth:
        depth += (source[end] == '{') - (source[end] == '}')
        end += 1
    return source[match.start():end] + '\n'


def verify_host(experiment):
    report = json.loads((experiment / 'result.json').read_text())
    copied = experiment / 'source-inputs'
    for name, digest in report['inputs'].items():
        if sha(copied / name) != digest:
            raise ValueError('Candidate source mismatch: ' + name)
    out = Path(tempfile.mkdtemp(prefix='host-review-', dir=experiment))
    definitions = (experiment / 'actual_owners.h').read_text()
    if 'uint8_t r0fg1_transport_prepare(' not in definitions:
        definitions += function((copied / PREFIX / 'group1_transport.c').read_text(),
                                'r0fg1_transport_prepare')
    (out / 'actual_owners.h').write_text(definitions)
    test = out / 'host_test.c'
    shutil.copyfile(ROOT / 'tools/diagnostics/r0f_group2_scratch_host_test.c', test)
    shutil.copyfile(Path(__file__), out / 'runner.py')
    command = report['commands'][0]['command'].copy()
    command[command.index('-I' + str(experiment))] = '-I' + str(out)
    test_index = next(i for i, value in enumerate(command)
                      if value.endswith(('r0f_group2_scratch_host_test.c', '/host_test.c')))
    command[test_index] = str(test)
    command[command.index('-o') + 1] = str(out / 'host')
    records = []
    for label, cmd in [('compile', command), ('run', [str(out / 'host')])]:
        result = subprocess.run(cmd, cwd=copied, text=True, capture_output=True, timeout=60)
        (out / (label + '.txt')).write_text(result.stdout + result.stderr)
        records.append({'command': cmd, 'exitCode': result.returncode})
        (out / 'validation.json').write_text(json.dumps(records, indent=2) + '\n')
        if result.returncode:
            print(result.stdout + result.stderr)
            print(out)
            return 1
    print((out / 'run.txt').read_text(), out)
    return 0


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--verify-host", type=Path)
    args = parser.parse_args()
    if args.verify_host:
        return verify_host(args.verify_host.resolve())
    baseline = json.loads((BASE / 'admission.json').read_text())
    source = BASE / 'source-inputs'
    for name, digest in baseline['inputs'].items():
        if sha(source / name) != digest:
            raise ValueError('Frozen admission mismatch: ' + name)
    parent = ROOT / 'build/r0f/group2/scratch'
    parent.mkdir(parents=True, exist_ok=True)
    out = Path(tempfile.mkdtemp(prefix='r1-', dir=parent))
    copied = out / 'source-inputs'
    shutil.copytree(source, copied)
    contract_path = 'interfaces/r0f_group2_scratch_contract.json'
    contract = json.loads((ROOT / contract_path).read_text())
    if contract['bytes'] != 255 or contract['symbol'] != 'r0fg2_foreground_scratch':
        raise ValueError('Unreviewed scratch contract')
    for name in (contract_path, 'memory/r0f-group2-scratch-memory-ledger.json'):
        shutil.copyfile(ROOT / name, copied / name)
    header = ('// Generated by r0f_group2_scratch.py from the private scratch contract.\n'
              '#ifndef R0FG2_SCRATCH_H\n#define R0FG2_SCRATCH_H\n#include <stdint.h>\n'
              f'#define R0FG2_SCRATCH_BYTES {contract["bytes"]}u\n'
              'extern uint8_t r0fg2_foreground_scratch[R0FG2_SCRATCH_BYTES];\n#endif\n')
    (copied / 'interfaces/generated/r0f_group2_scratch.h').write_text(header)
    for name, declaration, identifier in (
        ('combined_platform.c', 'uint8_t cfworkspace[255];\n#define check cfworkspace', 'check'),
        ('successor_integration.c', 'static uint8_t transfer[255];', 'transfer'),
        ('group1_transport.c', 'static uint8_t buffer[R0FG1X_COPY_CHUNK_BYTES];', 'buffer'),
    ):
        path = copied / PREFIX / name
        text = path.read_text()
        if text.count(declaration) != 1:
            raise ValueError('Ambiguous scratch declaration')
        replacement = ('uint8_t r0fg2_foreground_scratch[R0FG2_SCRATCH_BYTES];'
                       if name == 'combined_platform.c' else '')
        text = text.replace(declaration, replacement)
        text = re.sub(r'\b' + identifier + r'\b', 'r0fg2_foreground_scratch', text)
        text = '#include "r0f_group2_scratch.h"\n' + text
        if name == 'group1_transport.c':
            text += '\n_Static_assert(R0FG2_SCRATCH_BYTES == R0FG1X_COPY_CHUNK_BYTES, "copy capacity");\n'
        path.write_text(text)
    # Exact owner definitions; hardware I/O stays behind the test's PF boundary.
    platform = (copied / PREFIX / 'combined_platform.c').read_text()
    integration = (copied / PREFIX / 'successor_integration.c').read_text()
    transport = (copied / PREFIX / 'group1_transport.c').read_text()
    names = {
        'platform': ['cfput16', 'cfput32', 'cfget32', 'cfcopy', 'cfphysical_crc',
                     'cfrom_begin', 'cfrom_restore'],
        'integration': ['crc_update', 'fixed_physical_copy', 'dos_copy', 'dos_crc',
                        'display_seed_staging'],
        'transport': ['transfer', 'validate_capsule', 'r0fg1_transport_init',
                      'r0fg1_trace_write', 'r0fg1_trace_read', 'r0fg1_transport_prepare'],
    }
    extracted = ''.join(function(text, name) for key, text in
                        [('platform', platform), ('integration', integration),
                         ('transport', transport)] for name in names[key])
    start = integration.index('    for (index = 0u; index < sizeof(r0fg2_foreground_scratch);',
                              integration.index('// KERNAL/storage may leave text colors'))
    end = integration.index('    cfscreen();', start)
    extracted += ('static void terminal_colors(void)\n{\n    uint8_t index;\n'
                  + integration[start:end] + '}\n')
    (out / 'actual_owners.h').write_text(extracted)
    shutil.copyfile(Path(__file__), out / 'runner.py')
    shutil.copyfile(ROOT / 'tools/diagnostics/r0f_group2_scratch_host_test.c', out / 'host_test.c')
    report = {'result': 'FAIL', 'baseline': str(BASE), 'commands': [],
              'targetExecuted': False, 'carrier': 'NOT BUILT',
              'runnerSha256': sha(Path(__file__)), 'hostDefinitions': names}

    def run(label, command):
        result = subprocess.run(command, cwd=copied, capture_output=True,
                                text=True, timeout=60)
        (out / (label + '.txt')).write_text(result.stdout + result.stderr)
        report['commands'].append({'command': command, 'exitCode': result.returncode})
        result.check_returncode()

    try:
        host = out / 'host'
        run('host-compile', ['/usr/bin/clang', '-std=c11', '-Wall', '-Wextra', '-Werror',
            '-fsanitize=address,undefined', '-fno-sanitize-recover=all',
            '-Iinterfaces/generated', '-I' + PREFIX,
            '-I' + str(out), str(out / 'host_test.c'),
            PREFIX + 'combined_model.c', PREFIX + 'successor_lifecycle.c',
            PREFIX + 'group1_export.c', '-o', str(host)])
        run('host-run', [str(host)])
        command = next(c['command'].copy() for c in baseline['commands']
                       if 'mos-mega65-clang' in c['command'][0])
        compiler = Path(command[0])
        lock = json.loads((ROOT / 'toolchain/f65_toolchain.lock.json').read_text())
        if sha(compiler) != lock['llvm_mos']['compiler_sha256']:
            raise ValueError('Compiler mismatch')
        prg, mapping = out / 'R1.prg', out / 'R1.map'
        command[command.index('-o') + 1] = str(prg)
        command = ['-Wl,-Map,' + str(mapping) if c.startswith('-Wl,-Map,') else c
                   for c in command]
        run('target-compile', command)
        sections = section_inventory(mapping.read_text())
        end = max(sections[k]['start'] + sections[k]['bytes'] for k in
                  ('.r0fs_protected', '.text', '.rodata', '.data', '.bss', '.noinit'))
        report.update(sections=sections, residentEndExclusive=end,
                      residentFreeBytes=0xc000-end,
                      recoveredBytes=baseline['residentEndExclusive']-end,
                      prgSha256=sha(prg))
        if sections['.bss']['bytes'] != baseline['sections']['.bss']['bytes'] - 510:
            raise ValueError('Unexpected BSS saving')
        if sections['.r0fs_protected'] != baseline['sections']['.r0fs_protected']:
            raise ValueError('Protected region changed')
        for key in ('.data', '.rodata', '.noinit'):
            if sections[key]['bytes'] != baseline['sections'][key]['bytes']:
                raise ValueError('Unexpected allocation change: ' + key)
        run('sizes', [str(compiler.parent / 'llvm-nm'), '--print-size', '--size-sort', str(prg)+'.elf'])
        run('disassembly', [str(compiler.parent / 'llvm-objdump'), '-d', str(prg)+'.elf'])
        report['result'] = 'FIT_PASS_NOT_EXECUTABLE' if end <= 0xc000 else 'FIT_FAIL'
    except (ValueError, OSError, subprocess.SubprocessError) as error:
        report['error'] = str(error)
    finally:
        report['inputs'] = {str(p.relative_to(copied)): sha(p)
                            for p in sorted(copied.rglob('*')) if p.is_file()}
        report['baselineUnchanged'] = all(sha(source / k) == v for k, v in baseline['inputs'].items())
        report['changedInputs'] = [k for k, v in report['inputs'].items() if baseline['inputs'].get(k) != v]
        expected = {contract_path, 'memory/r0f-group2-scratch-memory-ledger.json',
                    'interfaces/generated/r0f_group2_scratch.h',
                    *(PREFIX + name for name in ('combined_platform.c',
                      'successor_integration.c', 'group1_transport.c'))}
        if not report['baselineUnchanged'] or set(report['changedInputs']) != expected:
            report['result'] = 'FAIL'
            report['error'] = 'Unexpected source or baseline change'
        (out / 'result.json').write_text(json.dumps(report, indent=2)+'\n')
        print(json.dumps({k: report.get(k) for k in
                         ('result', 'residentFreeBytes', 'recoveredBytes', 'error')}))
        print(out)
    return 0 if report['result'] == 'FIT_PASS_NOT_EXECUTABLE' else 1


if __name__ == '__main__':
    raise SystemExit(main())
