package f65.tools;

import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.*;
import java.util.*;
import java.util.regex.*;

public final class R0AHostTools {
  private static final Pattern RECORD = Pattern.compile("\\{\\\"name\\\": \\\"([^\\\"]+)\\\", \\\"size\\\": (\\d+)");
  private static String hash(byte[] input) throws Exception { return HexFormat.of().formatHex(MessageDigest.getInstance("SHA-256").digest(input)); }
  private static Map<String,Integer> records(Path root) throws Exception { String text=Files.readString(root.resolve("interfaces/f65_interfaces.json5")); Map<String,Integer> r=new LinkedHashMap<>(); Matcher m=RECORD.matcher(text); while(m.find())r.put(m.group(1),Integer.parseInt(m.group(2))); if(r.size()!=4)throw new IllegalStateException("invalid interface registry"); return r; }
  private static void write(Path p,String s)throws Exception{Files.createDirectories(p.getParent());Files.writeString(p,s,StandardCharsets.UTF_8);}
  private static boolean farPtr(long value){return value==0||(value>=0&&value<=0x0fffffffL);}
  private static boolean range(long address,long length){return farPtr(address)&&length>=0&&length<=0x10000000L&&address+length<=0x10000000L;}
  private static void generate(Path root)throws Exception{
    Map<String,Integer> r=records(root);String h=hash(Files.readAllBytes(root.resolve("interfaces/f65_interfaces.json5")));StringBuilder c=new StringBuilder("/* Generated by R0AHostTools; source SHA-256: "+h+" */\n#pragma once\n#include <stdint.h>\n");StringBuilder a=new StringBuilder("; Generated by R0AHostTools; source SHA-256: "+h+"\n");StringBuilder j=new StringBuilder("// Generated by R0AHostTools; source SHA-256: "+h+"\npackage f65.generated; public final class R0AInterfaces { private R0AInterfaces() {}\n");
    for(var e:r.entrySet()){String n=e.getKey().replaceAll("([a-z])([A-Z])","$1_$2").toUpperCase();c.append("#define R0A_").append(n).append("_SIZE ").append(e.getValue()).append("u\ntypedef struct { uint8_t bytes[").append(e.getValue()).append("]; } R0A_").append(e.getKey()).append(";\n");a.append("R0A_").append(n).append("_SIZE = ").append(e.getValue()).append("\n");j.append("public static final int ").append(n).append("_SIZE=").append(e.getValue()).append(";\n");}
    j.append("}\n");write(root.resolve("interfaces/generated/r0a_interfaces.h"),c.toString());write(root.resolve("interfaces/generated/r0a_interfaces.inc"),a.toString());write(root.resolve("interfaces/generated/R0AInterfaces.java"),j.toString());
  }
  private static void hostTest(Path root)throws Exception{if(!farPtr(0)||!farPtr(0x0fffffffL)||farPtr(0x10000000L)||!range(0x0ffffffeL,2)||range(0x0ffffffeL,3))throw new IllegalStateException("FarPtr32 oracle failure");write(root.resolve("build/r0a/reports/r0a-host-oracle.json"),"{\n  \"test\": \"R0A-PTR-001\",\n  \"status\": \"PASS\",\n  \"seed\": 65065,\n  \"vectors\": 10,\n  \"resource_handle_invalid\": 65535\n}\n");System.out.println("R0A-PTR-001 PASS: FarPtr32 boundary oracle");System.out.println("R0A-RES-001 PASS: ResourceHandle16 sentinel oracle");}
  public static void main(String[] args)throws Exception{if(args.length!=2)throw new IllegalArgumentException("mode root");Path root=Path.of(args[1]);if(args[0].equals("generate"))generate(root);else if(args[0].equals("host-test"))hostTest(root);else throw new IllegalArgumentException("mode");}
}
