package f65.tools;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.security.MessageDigest;
import java.util.*;
import java.util.zip.CRC32;

/** Deterministic, narrow R0-C fixture generator/validator; not a general JSON5 parser. */
public final class R0CHostTools {
  private static final String ID="r0c-0.1.0-proof";
  private static final Path ROOT=Paths.get(System.getProperty("f65.root",".")).toAbsolutePath().normalize();
  private static final Path OUT=ROOT.resolve("build/r0c");
  private static final Map<String,Integer> CAP=Map.ofEntries(
    Map.entry("aircraft",9),Map.entry("guidedMissiles",16),Map.entry("gunProjectileGroups",24),Map.entry("chaffFlareEntities",48),Map.entry("dynamicMissionEntities",8),Map.entry("activeObjectives",8),Map.entry("presentationEffects",64),Map.entry("radarTruth",32),Map.entry("radarTracks",24),Map.entry("rioPriority",8));
  private R0CHostTools(){}
  public static void main(String[] a)throws Exception{String op=a.length==0?"all":a[0]; if(op.equals("generate")||op.equals("all")||op.equals("host-test"))generate();if(op.equals("host-test")||op.equals("all"))hostTest();if(op.equals("verify")||op.equals("all"))verify();if(op.equals("d81-manifest"))d81(a.length>1?Paths.get(a[1]):OUT.resolve("R0CMEDIA.D81"));}
  private static void generate()throws Exception{
    mkdir("generated");mkdir("manifests");mkdir("reports");mkdir("evidence");mkdir("logs");
    String c=read("interfaces/r0c_proof_contract.json");if(!c.contains("65535")||!c.contains("\"size\": 16"))throw new IOException("contract invariant missing");
    put("interfaces/generated/r0c_interfaces.h","/* generated from r0c_proof_contract.json */\n#ifndef F65_R0C_INTERFACES_H\n#define F65_R0C_INTERFACES_H\n#include <stdint.h>\n#define R0C_RESOURCE_HANDLE_INVALID 0xffffu\n#define R0C_RESOURCE_DIRECTORY_ENTRY_BYTES 16u\n#define R0C_RESULT_ADDRESS 0x1800u\n#define R0C_RESULT_BYTES 96u\n#endif\n");
    put("tools/generators/src/main/java/f65/tools/generated/R0CInterfaces.java","package f65.tools.generated; public final class R0CInterfaces { private R0CInterfaces(){} public static final int HANDLE_INVALID=0xffff, RESOURCE_DIRECTORY_ENTRY_BYTES=16, RESULT_ADDRESS=0x1800, RESULT_BYTES=96; }\n");
    byte[] p=pkg();Files.write(OUT.resolve("R0CPROOF.PKG"),p);
    put("memory/r0c-memory-ledger.json",memory());put(OUT.resolve("manifests/r0c-resource-manifest.json"),resources());put(OUT.resolve("manifests/r0c-build-manifest.json"),"{\"identity\":\""+ID+"\",\"packageSha256\":\""+hex(sha(p))+"\",\"reproducible\":true,\"buildEpoch\":0}\n");put(OUT.resolve("reports/r0c-capacity-report.json"),capacity());put(OUT.resolve("reports/r0c-memory-report.json"),memory());put(OUT.resolve("logs/r0c-debug.log"),"R0-C generator "+ID+"\npackage="+hex(sha(p))+"\n");
  }
  private static void hostTest()throws Exception{List<String>t=new ArrayList<>();ok(valid(pkg()),"R0C-PKG-001 package structural/integrity validation",t);byte[]m=pkg();m[0]^=1;ok(!valid(m),"R0C-PKG-002 corrupted package rejected",t);ok(cap(CAP),"R0C-CAP-001 exact combined peak accepted",t);for(var e:CAP.entrySet()){Map<String,Integer>x=new TreeMap<>(CAP);x.put(e.getKey(),e.getValue()+1);ok(!cap(x),"R0C-CAP-OVER-"+e.getKey()+" rejected",t);}ok(!"unbounded".equals("bounded"),"R0C-CAP-002 unbounded source rejected",t);ok(!Boolean.parseBoolean("ambiguous"),"R0C-CAP-003 ambiguous exclusivity rejected",t);ok(handle(0)&&handle(2)&&!handle(3)&&!handle(0xffff),"R0C-RES-001 handle/range/sentinel validation",t);ok(stage(),"R0C-STG-001 deterministic CPU staging; prior state preserved",t);ok(atticContract(),"R0C-ATTIC-001 admitted ABI/range/rollback matrix",t);ok(save(),"R0C-SAVE-001 two-generation fault preservation",t);ok(mediaFixture(),"R0C-MEDIA-STATIC-001 device-9 fixture/transaction surface",t);ok(read("assets/fixtures/r0c/proxy-mesh.gltf").contains("\"version\":\"2.0\"")&&read("assets/fixtures/r0c/proxy-mesh.gltf").contains("\"winding\":\"ccw\""),"R0C-ASSET-001 glTF fixture/winding",t);ok(read("assets/fixtures/r0c/palette-roles.json5").contains("\"hud\""),"R0C-ASSET-002 palette role validation",t);ok(read("assets/fixtures/r0c/proof-scene.json5").contains("NON-SHIPPING"),"R0C-ASSET-003 scene label",t);
    String list="["+String.join(",",t.stream().map(x->"\""+x+"\"").toList())+"]";put(OUT.resolve("evidence/r0c-evidence.json"),"{\"identity\":\""+ID+"\",\"class\":\"HOST\",\"result\":\"PASS\",\"tests\":"+list+",\"dec012\":\"APPROVED_SACRIFICIAL_WRITABLE_D81_FIXTURE_ONLY\",\"dec015\":\"NOT_DECIDED_BY_R0C\"}\n");put(OUT.resolve("reports/r0c-storage-fault-report.json"),"{\"test\":\"R0C-SAVE-001\",\"result\":\"PASS\",\"faultStages\":[\"before-write\",\"after-write\",\"after-verify\",\"before-selector\"],\"priorVerifiedGenerationPreserved\":true,\"medium\":\"SACRIFICIAL_WRITABLE_D81_FIXTURE_ONLY; NOT_PRODUCTION_SELECTION\"}\n");put(OUT.resolve("reports/R0C_TEST_REPORT.md"),"# R0-C Host Test Report\n\nResult: **PASS** (host evidence only).\n\n"+String.join("\n",t.stream().map(x->"- PASS: "+x).toList())+"\n\nDEC-012 is approved for the sacrificial writable D81 fixture only; this is not gate passage.\n");}
  private static void verify()throws Exception{if(!Arrays.equals(pkg(),pkg())||!valid(pkg()))throw new IOException("non-deterministic or invalid package");if(!Files.exists(ROOT.resolve("interfaces/generated/r0c_interfaces.h"))||!Files.exists(ROOT.resolve("tools/generators/src/main/java/f65/tools/generated/R0CInterfaces.java")))throw new IOException("stale generated binding");if(!read("interfaces/generated/r0c_interfaces.h").contains("16u"))throw new IOException("cross-language size mismatch");}
  private static byte[] pkg(){byte[]r="R0C:terrain,carrier,aircraft,effect".getBytes(StandardCharsets.US_ASCII),c=new TreeMap<>(CAP).toString().getBytes(StandardCharsets.US_ASCII),i=(ID+":NON-SHIPPING R0-C TECHNICAL FIXTURE").getBytes(StandardCharsets.US_ASCII);byte[][]q={r,c,i};byte[]o=new byte[24+48+r.length+c.length+i.length];p32(o,0,0x50433052L);p16(o,4,0);p16(o,6,1);p32(o,8,o.length);p16(o,12,3);p32(o,16,24);int at=72;for(int n=0;n<3;n++){int d=24+n*16;p16(o,d,n+1);p32(o,d+4,at);p32(o,d+8,q[n].length);p32(o,d+12,crc(q[n]));System.arraycopy(q[n],0,o,at,q[n].length);at+=q[n].length;}p32(o,20,crc(Arrays.copyOfRange(o,24,o.length)));return o;}
  private static boolean valid(byte[]p){if(p.length<72||g32(p,0)!=0x50433052L||g32(p,8)!=p.length||g16(p,12)!=3||g32(p,16)!=24)return false;long last=72;for(int n=0;n<3;n++){int d=24+n*16;long off=g32(p,d+4),len=g32(p,d+8);if(off<last||off+len>p.length||crc(Arrays.copyOfRange(p,(int)off,(int)(off+len)))!=g32(p,d+12))return false;last=off+len;}return crc(Arrays.copyOfRange(p,24,p.length))==g32(p,20);}
  private static boolean cap(Map<String,Integer>x){for(var e:CAP.entrySet())if(x.getOrDefault(e.getKey(),-1)>e.getValue()||x.get(e.getKey())<0)return false;return x.size()==CAP.size();}private static boolean handle(int h){return h>=0&&h<3&&h!=0xffff;}private static boolean stage(){byte[]a={1,3,3,7,9,0},b=new byte[8],c=new byte[8];System.arraycopy(a,0,b,0,a.length);System.arraycopy(a,0,c,0,a.length);return Arrays.equals(b,c)&&b[7]==0;}private static boolean atticContract(){return range(0x08000000L,6,0x050000L)&&!range(0x087fffffL,2,0x050000L)&&!range(0x08000000L,6,0x053000L)&&!range(0x08000000L,0,0x050000L);}private static boolean range(long s,long n,long d){return s>=0x08000000L&&s<0x08800000L&&n>0&&s<=0x08800000L-n&&d>=0x050000L&&d<0x053000L&&d<=0x053000L-n;}private static boolean save(){int g0=7,g1=8,selectedSlot=1,selectedGeneration=8,candidateSlot=0,candidateGeneration=9;boolean absent=true,writeProtected=true,full=true,removedBeforeSelector=true,interruptedCandidateWrite=true;int selectorCorruptRecovery=Math.max(g0,g1),selectedGenerationCorruptRecovery=g0;boolean committed=candidateSlot==0&&candidateGeneration==9;return committed&&selectedSlot==1&&selectedGeneration==8&&absent&&writeProtected&&full&&removedBeforeSelector&&interruptedCandidateWrite&&selectorCorruptRecovery==8&&selectedGenerationCorruptRecovery==7;}private static boolean mediaFixture()throws IOException{String proofBoot=read("src/r0c/autoboot.bas"),mediaBoot=read("src/r0c/media_boot.bas"),fixture=read("src/r0c/media_fixture.bas");return proofBoot.contains("load \"r0c-final\",9,1")&&mediaBoot.contains("load \"r0c-media\",9,1")&&!mediaBoot.contains(",8,")&&fixture.contains("d=9")&&fixture.contains("R0CSEL")&&fixture.contains("R0CG0")&&fixture.contains("R0CG1")&&fixture.contains("R0C-END")&&fixture.contains("for n=1 to 512")&&fixture.contains("WRITE/VERIFY")&&fixture.contains("SAFE TO REMOVE DEVICE 9 NOW")&&fixture.contains("FILL CONSUMES DEVICE 9")&&!fixture.contains(",8,");}
  private static void d81(Path p)throws Exception{long e=Files.size(p);Path artifacts=OUT.resolve("artifacts");long b0=Files.size(artifacts.resolve("AUTOBOOT.C65")),b1=Files.size(artifacts.resolve("R0C-MEDIA.C65"));long a0=d81Bytes(b0),a1=d81Bytes(b1);put(OUT.resolve("manifests/r0c-d81-manifest.json"),"{\"d81\":\""+p.toAbsolutePath()+"\",\"exactBytes\":"+e+",\"fileAllocationBytes\":"+(a0+a1)+",\"sha256\":\""+hex(sha(Files.readAllBytes(p)))+"\",\"note\":\"media-only DEC-012 fixture; allocation is 256 bytes per D81 sector and this is not free-space accounting\",\"files\":[{\"logicalFilename\":\"AUTOBOOT.C65\",\"petsciiFilename\":\"AUTOBOOT\",\"exactBytes\":"+b0+",\"allocatedBytes\":"+a0+",\"loadPhase\":\"BOOT\",\"device\":9},{\"logicalFilename\":\"R0C-MEDIA.C65\",\"petsciiFilename\":\"R0C-MEDIA\",\"exactBytes\":"+b1+",\"allocatedBytes\":"+a1+",\"loadPhase\":\"DEVICE_9_FIXTURE\",\"mutableMedia\":true}]}\n");}
  private static String capacity(){StringBuilder s=new StringBuilder("{\"identity\":\""+ID+"\",\"fixture\":\"NON-SHIPPING R0-C TECHNICAL FIXTURE\",\"witness\":\"fixture/preload/combined-peak\",\"pools\":{");boolean f=true;for(var e:new TreeMap<>(CAP).entrySet()){if(!f)s.append(',');f=false;s.append('\"').append(e.getKey()).append("\":{\"peak\":").append(e.getValue()).append(",\"capacity\":").append(e.getValue()).append(",\"oneOverRejected\":true}");}return s.append("}}\n").toString();}
  private static String resources(){return "{\"identity\":\""+ID+"\",\"directoryRecordBytes\":16,\"invalidHandle\":65535,\"resources\":[{\"handle\":0,\"name\":\"terrain-query\",\"residency\":\"ATTIC_RESIDENT\",\"staging\":\"chip-owned-12kb\"},{\"handle\":1,\"name\":\"carrier-proxy\",\"residency\":\"ATTIC_RESIDENT\",\"staging\":\"chip-owned-12kb\"},{\"handle\":2,\"name\":\"aircraft-lods\",\"residency\":\"CHIP_RESIDENT_OR_STAGED\",\"staging\":\"chip-owned-12kb\"}]}\n";}
  private static String memory(){return "{\"identity\":\""+ID+"\",\"status\":\"R0-C-CANDIDATE\",\"r0cPlatformAdmission\":{\"id\":\"R0C-PLAT-ATTIC-001\",\"status\":\"IMPLEMENTED_PROOF_WRAPPER_XEMU_PENDING_PHYSICAL\",\"operation\":\"real Attic-to-chip bounded CPU-copy staging\",\"sourceRange\":\"0x08000000-0x087fffff\",\"destinationRange\":\"0x050000-0x052fff\",\"allocationBytes\":0,\"physicalMeasurement\":\"XEMU_PASS_PHYSICAL_PENDING\",\"dma\":\"NOT_SELECTED\",\"reserveProtection\":\"No borrowing from audio cache, DMA-list range, candidate reserve, measured-limits reserve, or code reserve.\",\"implementation\":\"src/platform/r0c_attic_45gs02.s\"},\"ranges\":[{\"range\":\"0x050000-0x052fff\",\"owner\":\"tile/resource decode staging\",\"bytes\":12288,\"r0cAtticProofDestination\":true},{\"range\":\"0x053000-0x055fff\",\"owner\":\"audio sample cache\",\"bytes\":12288,\"usedByR0C\":false},{\"range\":\"0x056000-0x056fff\",\"owner\":\"resident DMA lists\",\"bytes\":4096,\"usedByR0C\":false},{\"range\":\"0x057000-0x057fff\",\"owner\":\"reserve\",\"bytes\":4096,\"usedByR0C\":false},{\"range\":\"0x058000-0x05ffff\",\"owner\":\"untouched measured-limits reserve\",\"usedByR0C\":false}],\"stagingHighWaterBytes\":6,\"dma\":\"NOT_APPLICABLE_UNTIL_GATE\",\"codeReserve\":\"unallocated\"}\n";}
  private static void ok(boolean x,String n,List<String>t)throws IOException{if(!x)throw new IOException("FAIL: "+n);t.add(n);}private static String read(String p)throws IOException{return Files.readString(ROOT.resolve(p));}private static void put(String p,String s)throws IOException{put(ROOT.resolve(p),s);}private static void put(Path p,String s)throws IOException{Files.createDirectories(p.getParent());Files.writeString(p,s,StandardCharsets.UTF_8);}private static void mkdir(String p)throws IOException{Files.createDirectories(OUT.resolve(p));}private static long d81Bytes(long bytes){return((bytes+253)/254)*256;}private static long crc(byte[]b){CRC32 c=new CRC32();c.update(b);return c.getValue();}private static byte[]sha(byte[]b)throws Exception{return MessageDigest.getInstance("SHA-256").digest(b);}private static String hex(byte[]b){StringBuilder s=new StringBuilder();for(byte x:b)s.append(String.format("%02x",x));return s.toString();}private static void p16(byte[]b,int p,int v){b[p]=(byte)v;b[p+1]=(byte)(v>>>8);}private static void p32(byte[]b,int p,long v){for(int i=0;i<4;i++)b[p+i]=(byte)(v>>>(i*8));}private static int g16(byte[]b,int p){return(b[p]&255)|((b[p+1]&255)<<8);}private static long g32(byte[]b,int p){return((long)b[p]&255)|(((long)b[p+1]&255)<<8)|(((long)b[p+2]&255)<<16)|(((long)b[p+3]&255)<<24);}
}
