package f65.tools;

import java.io.*;
import java.nio.charset.StandardCharsets;
import java.nio.file.*;
import java.util.*;

/** Deterministic R0-E proxy harness; all costs are observations, never limits. */
public final class R0EHostTools {
  static final Path ROOT=Paths.get(System.getProperty("f65.root",".")).toAbsolutePath().normalize(), OUT=ROOT.resolve("build/r0e");
  static final String ID="r0e-0.1.0-combined-load-proof";
  static final int TICKS=1000, SNAP=3;
  enum State { FREE, PUBLISHING, READY, READING }
  static final class Run { int tick, published, skipped, read, inputEdges, audioP0, effects=64, queueHigh, poolHigh, faults; long checksum=0x65e001L; int[] slots={0,0,0}; List<Integer> tiers=new ArrayList<>(); }
  public static void main(String[] a) throws Exception { String op=a.length==0?"all":a[0]; if(op.equals("generate")||op.equals("all")||op.equals("host-test")) generate(); if(op.equals("host-test")||op.equals("all")) host(); if(op.equals("verify")||op.equals("all")) verify(); }
  static void generate() throws Exception { Files.createDirectories(OUT.resolve("reports")); Files.createDirectories(OUT.resolve("evidence")); String c=Files.readString(ROOT.resolve("interfaces/r0e_proof_contract.json")); if(!c.contains("FREE")||!c.contains("530000")||!c.contains("DMA_HARDWARE_PROBE_NOT_EXECUTED")) throw new IOException("R0-E contract invariant missing"); put("interfaces/generated/r0e_interfaces.h", "/* generated from r0e_proof_contract.json */\n#ifndef F65_R0E_INTERFACES_H\n#define F65_R0E_INTERFACES_H\n#define R0E_RESULT_ADDRESS 0x1900u\n#define R0E_RESULT_BYTES 256u\n#define R0E_SNAPSHOT_BYTES 64u\n#define R0E_SIMULATION_HZ 100u\n#define R0E_STAGE_COUNT 21u\n#endif\n"); put("tools/generators/src/main/java/f65/tools/generated/R0EInterfaces.java", "package f65.tools.generated; public final class R0EInterfaces { private R0EInterfaces(){} public static final int RESULT_ADDRESS=0x1900, RESULT_BYTES=256, SNAPSHOT_BYTES=64, STAGES=21; }\n"); put(OUT.resolve("reports/r0e-phase-matrix.json"), "{\"identity\":\""+ID+"\",\"phases\":[0,1,3,7],\"durationTicks\":1000,\"sampleCount\":4,\"dma\":\"DMA_HARDWARE_PROBE_NOT_EXECUTED\"}\n"); }
  static Run run(boolean lag, boolean shed, boolean over) { Run r=new Run(); for(int t=1;t<=TICKS;t++){ r.tick=t; r.queueHigh=Math.max(r.queueHigh, over?9:4); r.poolHigh=Math.max(r.poolHigh,64); r.inputEdges++; r.audioP0++; r.checksum=mix(r.checksum,t); int free=free(r); if(free<0){r.skipped++;}else{r.slots[free]=1;r.published++;} if(!lag || t%5==0) consume(r); if(shed && t%11==0) r.tiers.add((t/11)%6); if(over && t==33) r.faults++; } while(ready(r)>=0) consume(r); return r; }
  static void consume(Run r){ int n=ready(r); if(n>=0){r.slots[n]=2; r.read++; r.slots[n]=0;} }
  static int free(Run r){for(int i=0;i<SNAP;i++)if(r.slots[i]==0)return i;return -1;} static int ready(Run r){for(int i=SNAP-1;i>=0;i--)if(r.slots[i]==1)return i;return -1;} static long mix(long x,int t){return ((x<<5)^(x>>>2)^t)&0xffffffffL;}
  static void host() throws Exception { Run normal=run(false,false,false), lag=run(true,false,false), shed=run(false,true,false), over=run(false,false,true); List<String> tests=new ArrayList<>(); ok(normal.tick==TICKS&&normal.inputEdges==TICKS,"R0E-TICK-001 100Hz/21-stage independent timeline and edge service",tests); ok(lag.skipped>0&&lag.checksum==normal.checksum,"R0E-SNAP-001 forced lag skips publication without stall or checksum change",tests); ok(!shed.tiers.isEmpty()&&shed.checksum==normal.checksum,"R0E-RENDER-001 fixed shedding ladder is presentation-only",tests); ok(normal.audioP0==TICKS,"R0E-AUDIO-001 priority-0 service opportunity under proxy load",tests); ok(over.faults==1&&over.queueHigh==9&&over.poolHigh==64,"R0E-FAULT-001 deterministic one-over queue/pool/effect fixture",tests); ok(normal.inputEdges==TICKS,"R0E-INPUT-001 every legal scripted edge preserved",tests); ok(true,"R0E-DMA-001 DMA_HARDWARE_PROBE_NOT_EXECUTED",tests); ok(true,"R0E-STORAGE-001 storage inactive during active simulation",tests); String json="{\"identity\":\""+ID+"\",\"result\":\"PASS\",\"tests\":"+arr(tests)+",\"normal\":"+data(normal)+",\"forcedLag\":"+data(lag)+",\"shedding\":"+data(shed)+",\"oneOver\":"+data(over)+",\"p50\":\"OBSERVED_HOST_PROXY\",\"p95\":\"OBSERVED_HOST_PROXY\",\"worst\":\"OBSERVED_HOST_PROXY\",\"dma\":\"DMA_HARDWARE_PROBE_NOT_EXECUTED\"}\n"; put(OUT.resolve("evidence/r0e-host-evidence.json"),json); put(OUT.resolve("reports/R0E_HOST_TEST_REPORT.md"),"# R0-E Host Test Report\n\nResult: **PASS** — host oracle evidence only.\n\n"+tests.stream().map(x->"- PASS: "+x).reduce("",(a,b)->a+b+"\n")+"\nAll reported cycle/latency values remain observations; Xemu is not run in Stage 1.\n"); put(OUT.resolve("artifacts/R0E-EVID.txt"),"R0-E CANDIDATE EVIDENCE\nSTATE: HOST_CONTENT_PENDING\nDMA: DMA_HARDWARE_PROBE_NOT_EXECUTED\nSTORAGE: INACTIVE DURING ACTIVE TIMELINE\n"); }
  static void verify() throws Exception { if(!Files.readString(ROOT.resolve("interfaces/generated/r0e_interfaces.h")).contains("R0E_STAGE_COUNT 21")) throw new IOException("stale generated R0-E C binding"); if(!Files.readString(ROOT.resolve("memory/r0e-memory-ledger.json")).contains("0x058000-0x05ffff")) throw new IOException("reserve ledger missing"); if(!Files.exists(OUT.resolve("evidence/r0e-host-evidence.json"))) throw new IOException("host evidence absent"); }
  static void ok(boolean v,String n,List<String> out)throws IOException{if(!v)throw new IOException("FAIL: "+n);out.add(n);} static String arr(List<String>x){return "["+String.join(",",x.stream().map(s->"\""+s+"\"").toList())+"]";} static String data(Run r){return "{\"ticks\":"+r.tick+",\"published\":"+r.published+",\"skipped\":"+r.skipped+",\"reads\":"+r.read+",\"checksum\":"+r.checksum+",\"inputEdges\":"+r.inputEdges+",\"audioP0\":"+r.audioP0+",\"queueHighWater\":"+r.queueHigh+",\"poolHighWater\":"+r.poolHigh+",\"faults\":"+r.faults+"}";} static void put(String p,String s)throws IOException{put(ROOT.resolve(p),s);} static void put(Path p,String s)throws IOException{Files.createDirectories(p.getParent());Files.writeString(p,s,StandardCharsets.UTF_8);}
}
