"""Generate the private trace layout; validate its storage and field bounds."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "interfaces/r0f_group1_trace_contract.json"


def validate_fields(fields, capacity, widths, default_width):
    occupied = set()
    for name, offset in fields.items():
        width = widths.get(name, default_width)
        extent = set(range(offset, offset + width))
        if offset < 0 or offset + width > capacity or occupied & extent:
            raise ValueError("field overlap/bounds: " + name)
        occupied |= extent


def validate(contract, export):
    c = contract["constants"]
    records = c["EPOCHS"] * c["PHASES"] * c["TICKS_PER_PHASE"]
    if (c["EPOCHS"] != 2 or c["STAGES"] != 21 or c["TICKS_PER_PHASE"] != 100
            or not 1 <= c["PHASES"] <= 255 or not 1 <= records <= 65535
            or c["HEADER_BYTES"] != 256 or c["RESULT_BYTES"] != 512
            or c["WORLD_EVENT_BYTES"] != 8 or not 1 <= c["MAX_WORLD_EVENTS"] <= 65535
            or not 1 <= c["RECORD_BYTES"] <= 255):
        raise ValueError("unsupported acquisition geometry")
    length = c["HEADER_BYTES"] + records * c["RECORD_BYTES"] + c["RESULT_BYTES"] + c["MAX_WORLD_EVENTS"] * c["WORLD_EVENT_BYTES"] + 4
    if length > export["constants"]["TRACE_CAPACITY"]:
        raise ValueError("trace exceeds admitted allocation")
    # Wire widths are protocol types. Values/placement remain contract-owned.
    words32 = {"RELEASE", "START", "PUBLICATION", "END", "WORLD_SWAP_TIME", "PREVIOUS_CAPTURE_COUNTS"}
    bytes8 = {"EPOCH", "PHASE", "SNAPSHOT_HIGH", "QUEUE_HIGH", "ENTRY_STACK_POINTER", "FLAGS"}
    widths = {**dict.fromkeys(words32, 4), **dict.fromkeys(bytes8, 1), "STAGE_COUNTS": c["STAGES"] * 2}
    validate_fields(contract["recordOffsets"], c["RECORD_BYTES"], widths, 2)
    widths = {**dict.fromkeys(("REFERENCE", "VIDEO", "CPU_SPEED", "BASE_PAGE", "LIVE_SIX_DOF", "LIVE_KINEMATIC"), 1),
              **dict.fromkeys(("VERSION", "RECORD_BYTES", "HARDWARE_STACK", "SOFTWARE_STACK", "AI_CAUSALITY_ERRORS", "TRACK_HIGH"), 2),
              "PRE_FRAME_SAMPLES": 64, "POST_FRAME_SAMPLES": 64, "AI_RUNS": 6}
    validate_fields(contract["headerOffsets"], c["HEADER_BYTES"], widths, 4)
    return records, length


def generate():
    contract = json.loads(PATH.read_text())
    constants = contract["constants"]
    export = json.loads((ROOT / "interfaces/r0f_group1_export_contract.json").read_text())
    records, length = validate(contract, export)
    lines = ["/* Generated by r0f_group1_contract.py. */", "#ifndef R0FG1_TRACE_GENERATED_H", "#define R0FG1_TRACE_GENERATED_H"]
    for group, prefix in (("constants", ""), ("recordOffsets", "O_"), ("headerOffsets", "H_")):
        for name, value in contract[group].items():
            lines.append(f"#define R0FG1_{prefix}{name} {value}u")
    world_offset = length - constants["MAX_WORLD_EVENTS"] * constants["WORLD_EVENT_BYTES"] - 4
    lines += [f"#define R0FG1_RECORDS {records}u",
              f"#define R0FG1_TRACE_BYTES {length}ul",
              f"#define R0FG1_WORLD_OFFSET {world_offset}ul", "#endif", ""]
    (ROOT / "interfaces/generated/r0f_group1_trace.h").write_text("\n".join(lines))
    table = []
    for value in range(256):
        for _ in range(8):
            value = (value >> 1) ^ (0xedb88320 if value & 1 else 0)
        table.append(value)
    table_text = "/* Generated CRC32/ISO-HDLC byte table. */\nstatic const uint32_t crc_table[256] = {\n"
    table_text += "\n".join("    " + ", ".join(f"0x{value:08x}ul" for value in table[index:index + 4]) + "," for index in range(0, 256, 4))
    (ROOT / "interfaces/generated/r0f_group1_crc_table.inc").write_text(table_text + "\n};\n")
    return contract


if __name__ == "__main__":
    generate()
