"""Generate isolated private pool-fixture parameters, never production limits."""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
PATH = ROOT / "interfaces/r0f_group1_pool_contract.json"
HEADER = ROOT / "interfaces/generated/r0f_group1_pool.h"
POOL_NAMES = ("FACES", "VERTICES", "SPANS", "BUCKETS", "PCM_CHANNELS",
              "AUDIO_CACHE", "MEGA_TRACKS", "RED_TRACKS")


def validate(wire):
    if (wire["id"] != "R0FG1-POOL-OBSERVATION-2"
            or wire["status"] != "PRIVATE_DIAGNOSTIC_NOT_PRODUCTION_ABI_OR_MEASURED_LIMITS"
            or tuple(wire["pools"]) != POOL_NAMES):
        raise ValueError("unsupported private pool identity/units")
    stride = wire["fixtureParameters"]["OFFSET_STRIDE"]
    if type(stride) is not int or not 1 <= stride <= 65535:
        raise ValueError("invalid fixture stream stride")
    for pool in wire["pools"].values():
        capacity = pool["capacity"]
        if (type(capacity) is not int or not 1 <= capacity <= 65535
                or not isinstance(pool["unit"], str) or not pool["unit"].strip()):
            raise ValueError("invalid pool unit/capacity")
    if (wire["pools"]["PCM_CHANNELS"]["capacity"] != 4
            or wire["pools"]["MEGA_TRACKS"]["capacity"] != 24
            or wire["pools"]["RED_TRACKS"]["capacity"] != 24):
        raise ValueError("fixture contradicts fixed channel/domain counts")
    if [wire["pools"][name]["capacity"] for name in POOL_NAMES[:4]] != [16, 32, 32, 8]:
        raise ValueError("fixture geometry capacities changed")
    if wire["pools"]["AUDIO_CACHE"]["capacity"] != 255:
        raise ValueError("fixture cache capacity changed")
    if (wire["wire"] != {"RECORD_BYTES": 8, "FAULT": 113, "GEOMETRY_COUNT": 4}
            or wire["wireOffsets"] != {"CAPACITY": 0, "PEAK": 2, "SAMPLES": 4, "FULL_SAMPLES": 6}):
        raise ValueError("unsupported pool encoding")
    return wire["pools"]


def render(wire):
    pools = validate(wire)
    lines = ["/* Generated by r0f_group1_pool_contract.py. */",
             "/* Private fixture only, not production ABI/measured limits. */",
             "#ifndef R0FG1_POOL_GENERATED_H", "#define R0FG1_POOL_GENERATED_H",
             f"#define R0FG1_POOL_COUNT {len(pools)}u",
             f"#define R0FG1_POOL_OFFSET_STRIDE {wire['fixtureParameters']['OFFSET_STRIDE']}u"]
    lines += [f"#define R0FG1_POOL_{name} {value}u"
              for name, value in wire["wire"].items()]
    lines += [f"#define R0FG1_POOL_W_{name} {value}u"
              for name, value in wire["wireOffsets"].items()]
    lines += [f"#define R0FG1_POOL_EPOCH_BYTES {len(pools) * wire['wire']['RECORD_BYTES']}u"]
    for index, (name, pool) in enumerate(pools.items()):
        lines += [f"#define R0FG1_POOL_{name} {index}u",
                  f"#define R0FG1_POOL_{name}_CAPACITY {pool['capacity']}u"]
    lines += ["#define R0FG1_POOL_CAPACITIES { \\"]
    lines += [f"    R0FG1_POOL_{name}_CAPACITY, \\" for name in pools]
    lines += ["}", "#endif", ""]
    return "\n".join(lines)


def generate():
    wire = json.loads(PATH.read_text())
    HEADER.write_text(render(wire))
    return wire


if __name__ == "__main__":
    generate()
