#!/usr/bin/env python3
"""PF-001 development PRG qualification. Deliberately has no D81/SD operation."""
import hashlib
import json
import pathlib
import re
import signal
import subprocess
import sys
import time

ROOT = pathlib.Path(__file__).resolve().parents[2]
OUT = ROOT / "build/r0f/platform-qualification"
TOOLS = ROOT / "toolchain/runtime/llvm-mos/bin"
JAVA = pathlib.Path("/Users/slice/Documents/Codex/f65-megawing/toolchain/runtime/jdk-full/jdk-21.0.12+8/Contents/Home/bin")
CONTRACT = ROOT / "interfaces/r0f_platform_contract.json"
PRG = OUT / "R0F-PLATFORM.prg"
COMMANDS = []


def sha(path):
    return hashlib.sha256(path.read_bytes()).hexdigest()


def run(args, **kwargs):
    args = list(map(str, args))
    COMMANDS.append(args)
    return subprocess.run(args, cwd=ROOT, check=True, **kwargs)


def pin(path, expected):
    if sha(path) != expected:
        raise ValueError("tool/input identity: " + str(path))


def build():
    OUT.mkdir(parents=True, exist_ok=True)
    contract = json.loads(CONTRACT.read_text())
    header = "/* Generated by r0f_platform_build.py; source r0f_platform_contract.json. */\n"
    header += "#ifndef R0F_PLATFORM_H\n#define R0F_PLATFORM_H\n"
    header += "".join(f"#define R0FP_{key} {value}u\n" for key, value in contract["constants"].items())
    header += "".join(f"#define R0FP_O_{key.upper()} {value}u\n" for key, value in contract["result"]["offsets"].items())
    header += "#endif\n"
    (ROOT / "interfaces/generated/r0f_platform.h").write_text(header)
    common = ROOT / "src/diagnostics/r0f/platform_model.c"
    run(["/usr/bin/clang", "-std=c11", "-Wall", "-Wextra", "-Wconversion", "-Werror",
         "-fsanitize=address,undefined", "-Iinterfaces/generated", common,
         "tools/diagnostics/r0f_platform_host_test.c", "-o", OUT / "host-test"])
    host = run([OUT / "host-test"], capture_output=True, text=True).stdout
    (OUT / "host-test.txt").write_text(host)
    print(host, flush=True)
    pin(TOOLS / "mos-mega65-clang", "cc557ae99a68ed36e098062b0f5376a878e94ac187b87446c8e603e4fb45a906")
    pin(TOOLS / "llvm-objdump", "5327f031a741bfcd4104317fbad3d1e45275d70b49821f0da52391120848a8e9")
    sources = ["src/diagnostics/r0f/platform_qualification.c", str(common.relative_to(ROOT)),
               "src/platform/r0f/qualification_45gs02.s", "src/platform/r0a_platform_45gs02.s"]
    run([TOOLS / "mos-mega65-clang", "-mcpu=mos45gs02", "-mlto-zp=0", "-Os",
         "-Wall", "-Wextra", "-Wconversion", "-Werror", "-Iinterfaces/generated", *sources,
         "-Wl,-T,src/platform/r0f/startup.ld", f"-Wl,-Map,{OUT/'R0F-PLATFORM.map'}", "-o", PRG])
    elf = pathlib.Path(str(PRG) + ".elf")
    for tool, args, suffix in [("llvm-nm", [], "symbols"), ("llvm-objdump", ["-d", "--print-imm-hex"], "disassembly")]:
        (OUT / ("R0F-PLATFORM." + suffix)).write_bytes(run([TOOLS/tool, *args, elf], capture_output=True).stdout)
    dis = (OUT / "R0F-PLATFORM.disassembly").read_text()
    if re.search(r"\b(?:jsr|jmp)\s+\$[ef][0-9a-f]{3}\b", dis):
        raise ValueError("ROM call/tail call found")
    mapping = (OUT / "R0F-PLATFORM.map").read_text()
    sections = {}
    for name in (".basic_header", ".text", ".rodata", ".data", ".bss", ".noinit", ".zp.data", ".zp.bss"):
        match = re.search(r"^\s*([0-9a-f]+)\s+[0-9a-f]+\s+([0-9a-f]+)\s+\d+\s+" + re.escape(name) + r"$", mapping, re.M)
        if not match:
            raise ValueError("missing linked section " + name)
        start, size = map(lambda v: int(v, 16), match.groups())
        if size and (start < 0x2001 or start + size > 0x8000):
            raise ValueError("outside resident proof range " + name)
        sections[name] = {"start": start, "bytes": size}
    if "__stack = 0xd000" not in mapping:
        raise ValueError("software stack top")
    symbols = (OUT / "R0F-PLATFORM.symbols").read_text()
    for n in range(32):
        if not re.search(rf"^000000{n+2:02x} A __rc{n}$", symbols, re.M):
            raise ValueError("compiler scratch ABI changed")
    irq = dis.split("<r0f_pf_irq>:", 1)[1].split("<r0f_pf_nmi>:", 1)[0]
    if re.search(r"\b(?:jsr|map|eom)\b|\$d70[05]", irq):
        raise ValueError("forbidden IRQ operation")
    for opcode in ("pha", "phx", "phy", "phz", "pla", "plx", "ply", "plz", "tab", "rti"):
        if not re.search(r"\b" + opcode + r"\b", irq):
            raise ValueError("IRQ preservation sequence " + opcode)
    entry = dis.split("<r0f_pf_enter>:", 1)[1].split("<r0f_pf_start_irq>:", 1)[0]
    if not re.search(r"lda\s+#\$0\s*\n[^\n]*\btab\b\s*\n[^\n]*lda\s+#\$35\s*\n[^\n]*sta\s+\$1\b", entry):
        raise ValueError("CPU port write without B=0 (linker relaxation regression)")
    if not re.search(r"lda\s+#\$2\s*\n[^\n]*\btab\b", entry):
        raise ValueError("B=2 not restored before C")
    helper = dis.split("<r0f_pf_flat_copy>:", 1)[1].split("<r0f_pf_register_probe>:", 1)[0]
    if not re.search(r"lda[^\n]*r0f_pf_copy_ok[^\n]*\n[^\n]*\bplp\b\s*\n[^\n]*\brts\b", helper):
        raise ValueError("flat helper must preserve flags after loading A result")
    pin(JAVA / "java", "34b9c157bedcebafc6033b8beaa72c2ff14e2b697e33f45aa959a8373d6581a0")
    pin(JAVA / "javac", "ee7be919e8bc4f364a1de24c245eea5ff8bb8f5560c8eb182ad3e89007adb152")
    version = run([JAVA / "java", "-version"], capture_output=True).stderr.decode()
    if "Temurin-21.0.12+8" not in version:
        raise ValueError("Java version")
    (OUT / "classes").mkdir(exist_ok=True)
    oracle = "tools/generators/src/main/java/f65/tools/R0FPlatformOracle.java"
    run([JAVA / "javac", "-Xlint:all", "-Werror", "-d", OUT / "classes", oracle])
    inputs = sources + [str(CONTRACT.relative_to(ROOT)), "interfaces/generated/r0f_platform.h",
                        "interfaces/f65_platform_abi.json5", "memory/r0f-memory-ledger.json",
                        "docs/plans/r0-f-task-admission.json", "docs/plans/r0-f-ownership-map.json",
                        "docs/reports/R0-F_PLATFORM_QUALIFICATION_CONTRACT.md", "src/platform/r0f/startup.ld",
                        "tools/diagnostics/r0f_platform_host_test.c", "tools/diagnostics/r0f_platform_build.py", oracle]
    account = {"identity": "PF001-DEVELOPMENT-ONLY", "sourceCommit": run(["git", "rev-parse", "HEAD"], capture_output=True, text=True).stdout.strip(),
               "sourceState": "dirty working tree, per-input hashes authoritative", "sections": sections,
               "prgSha256": sha(PRG), "prgBytes": PRG.stat().st_size,
               "inputs": {p: sha(ROOT / p) for p in inputs},
               "stackTop": 0xd000, "dynamicHighWater": "NOT MEASURED", "reserveBytes": 0,
               "references": {p.name: sha(p) for p in (ROOT / "build/r0f/combined/references").glob("*")},
               "javaVersion": version, "javaSha256": sha(JAVA / "java"), "javacSha256": sha(JAVA / "javac"),
               "compilerSha256": sha(TOOLS / "mos-mega65-clang"),
               "commands": COMMANDS, "xemu": "NOT RUN", "physical": "NOT RUN", "combinedReady": False}
    (OUT / "accounting.json").write_text(json.dumps(account, indent=2) + "\n")
    print("PF001 compile/link/static PASS; no D81 or SD operation", flush=True)


def xemu():
    account = json.loads((OUT / "accounting.json").read_text())
    if sha(PRG) != account["prgSha256"] or any(sha(ROOT / p) != value for p, value in account["inputs"].items()):
        raise ValueError("build inputs changed; rebuild before Xemu")
    emulator = ROOT / "toolchain/xemu/xmega65"
    rom = pathlib.Path("/Users/slice/Documents/Codex/f65-megawing/MEGA65.ROM")
    base_sd = pathlib.Path("/Users/slice/Library/Application Support/xemu-lgb/mega65/mega65.img")
    pin(emulator, "dd37baf7846b9696adcb662ffe5da040031b07214c66aef9a7f48cc30040b738")
    pin(rom, "af3c447f791a2fdc48cb21e1bd3fab015e32641228d9d30d21259b9e878c6fa0")
    boots = []
    for boot in range(1, 3):
        directory = OUT / f"xemu-{boot}-{time.time_ns()}"
        directory.mkdir()
        run(["/bin/cp", PRG, OUT / "accounting.json", directory])
        sd = directory / "disposable-sd.img"
        # APFS copy-on-write clone: disposable whole-emulator SD image, NOT D81
        # construction or a physical-card copy. Refuse if cloning unavailable.
        run(["/bin/cp", "-c", base_sd, sd])
        # PCM playhead advancement occurs in the real-time SDL callback in this
        # pinned Xemu, not in emulated CPU time. Do not use -sleepless here.
        args = [str(emulator), "-skipconfigfile", "-headless", "-fastboot", "-videostd", "1",
                "-rom", str(rom), "-sdimg", str(sd), "-defd81fromsd", "-prg", str(PRG),
                "-dumpscreen", str(directory / "screen.txt"), "-dumpmem", str(directory / "memory.bin"),
                "-screenshot", str(directory / "screen.png")]
        with (directory / "xemu.log").open("wb") as log:
            process = subprocess.Popen(args, cwd=ROOT, stdout=log, stderr=subprocess.STDOUT)
            print(f"PF001 Xemu boot {boot} running: {directory}", flush=True)
            try:
                process.wait(timeout=35)
            except subprocess.TimeoutExpired:
                process.send_signal(signal.SIGTERM)
                process.wait(timeout=10)
        memory = (directory / "memory.bin").read_bytes()
        raw = directory / "result.bin"
        raw.write_bytes(memory[0x1900:0x1a00])
        # Save diagnostic output even if the oracle refuses qualification.
        check = subprocess.run([str(JAVA / "java"), "-cp", str(OUT / "classes"),
                                "f65.tools.R0FPlatformOracle", "--self-test", str(raw)], capture_output=True, text=True)
        (directory / "oracle.txt").write_text(check.stdout + check.stderr)
        evidence = {"directory": str(directory.relative_to(ROOT)), "command": args,
                    "resultSha256": sha(raw), "screenshotSha256": sha(directory / "screen.png"),
                    "resultHex": raw.read_bytes().hex(), "oracleExit": check.returncode}
        boots.append(evidence)
        (directory / "evidence.json").write_text(json.dumps(evidence, indent=2) + "\n")
        (OUT / "xemu.json").write_text(json.dumps({"boots": boots, "prgSha256": sha(PRG),
            "emulatorSha256": sha(emulator), "romSha256": sha(rom), "fullCombined": False,
            "tier": "direct PRG regression, not exact-D81 loadability or physical proof"}, indent=2) + "\n")
        print(check.stdout + check.stderr, flush=True)
        if check.returncode:
            raise ValueError("Xemu platform qualification failed; no D81/SD promotion")
    print("Two direct-PRG platform boots PASS; still not a combined D81", flush=True)


if __name__ == "__main__":
    if sys.argv[1:] == ["build"]:
        build()
    elif sys.argv[1:] == ["xemu"]:
        xemu()
    else:
        raise SystemExit("usage: r0f_platform_build.py build|xemu (never writes D81/physical SD)")
